module.exports = {
  build: require("./build"),
  compile: require("./compile"),
  config: require("./config"),
  console: require("./console"),
  create: require("./create"),
  dashboard: require("./dashboard"),
  db: require("./db"),
  debug: require("./debug"),
  deploy: require("./deploy"),
  develop: require("./develop"),
  exec: require("./exec"),
  help: require("./help"),
  init: require("./init"),
  install: require("./install"),
  migrate: require("./migrate"),
  networks: require("./networks"),
  obtain: require("./obtain"),
  opcode: require("./opcode"),
  preserve: require("./preserve"),
  publish: require("./publish"),
  run: require("./run"),
  test: require("./test"),
  unbox: require("./unbox"),
  version: require("./version"),
  watch: require("./watch")
};
