import { scopeSchemas } from "./utils";

import { abiItem, schema as artifactsSchema } from "truffle-db/artifacts";
import { schema as workspaceSchema } from "truffle-db/workspace";

import { readInstructions } from "./bytecode";

export const schema = scopeSchemas({
  subschemas: {
    artifacts: artifactsSchema,
    workspace: workspaceSchema,
  },
  typeDefs: [
    // manually add autogenerated ABI schema type to avoid having to define
    // this schema in more places than the extant JSON-Schema
    [abiItem],
    `extend type ABI {
      items: [AbiItem]
    }`
  ],
  resolvers: {
    Bytecode: {
      instructions: ({ bytes, sourceMap }) =>
        readInstructions(bytes, sourceMap)
    },
  }
});
