module.exports = {
  build: require("./build"),
  compile: require("./compile"),
  console: require("./console"),
  create: require("./create"),
  debug: require("./debug"),
  deploy: require("./deploy"),
  develop: require("./develop"),
  exec: require("./exec"),
  help: require("./help"),
  init: require("./init"),
  install: require("./install"),
  migrate: require("./migrate"),
  networks: require("./networks"),
  opcode: require("./opcode"),
  publish: require("./publish"),
  test: require("./test"),
  unbox: require("./unbox"),
  version: require("./version"),
  watch: require("./watch"),
};
