module.exports = {
  init: require("./init"),
  compile: require("./compile"),
  migrate: require("./migrate"),
  deploy: require("./deploy"),
  test: require("./test"),
  debug: require("./debug"),
  opcode: require("./opcode"),
  console: require("./console"),
  develop: require("./develop"),
  create: require("./create"),
  help: require("./help"),
  install: require("./install"),
  publish: require("./publish"),
  networks: require("./networks"),
  exec: require("./exec"),
  unbox: require("./unbox"),
  version: require("./version"),
  config: require("./config")
};
