module.exports = {
  init: require("./init"),
  compile: require("./compile"),
  migrate: require("./migrate"),
  build: require("./build"),
  test: require("./test"),
  install: require("./install"),
  publish: require("./publish"),
  console: require("./console"),
  create: require("./create"),
  networks: require("./networks"),
  digest: require("./digest"),
  exec: require("./exec"),
  watch: require("./watch"),
  serve: require("./serve"),
  version: require("./version"),
};
