module.exports = {
  init: require("./init"),
  compile: require("./compile"),
  migrate: require("./migrate"),
  deploy: require("./deploy"),
  build: require("./build"),
  test: require("./test"),
  console: require("./console"),
  create: require("./create"),
  install: require("./install"),
  publish: require("./publish"),
  //digest: require("./digest"),
  networks: require("./networks"),
  watch: require("./watch"),
  serve: require("./serve"),
  exec: require("./exec"),
  version: require("./version"),
};
